### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by heron2014** [react-native-club/react-native-redux-form-auth-example#5]
- [ ] check if token exist in the main App 
- [ ] redirect user to private screen if token exist
- [ ] send server request on login
- [ ] render server errors
